trigger:
  - master

pool:
  name: Myagent

stages:
  - stage: Build
    displayName: 'Build and Package'
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - script: mvn clean package

  - stage: Test
    displayName: 'Run Tests'
    jobs:
      - job: Test
        displayName: 'Test'
        steps:
          - script: mvn test